/* Existing report layout, with data-only replacement markers. */
static const char report_template[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "  <meta charset=\"utf-8\"/>\n"
  "  <title>Pi MITM token report</title>\n"
  "  <style>\n"
  "    :root { color-scheme: dark; }\n"
  "    body { margin: 0; font-family: ui-sans-serif, system-ui, sans-serif;\n"
  "           background: #0b1014; color: #e8eef5; line-height: 1.45; }\n"
  "    main { max-width: 1100px; margin: 0 auto; padding: 32px 20px 64px; }\n"
  "    h1, h2 { font-weight: 600; }\n"
  "    h1 { font-size: 1.6rem; margin-bottom: 0.3rem; }\n"
  "    .muted { color: #8aa0b4; }\n"
  "    .cards { display: grid; gap: 12px; margin: 20px 0 28px;\n"
  "              grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }\n"
  "    .card { background: #151c24; border: 1px solid #243040;\n"
  "             border-radius: 10px; padding: 14px 16px; }\n"
  "    .card .n { font-size: 1.35rem; font-variant-numeric: tabular-nums; }\n"
  "    table { width: 100%; border-collapse: collapse; font-size: 0.92rem; }\n"
  "    th, td { text-align: left; padding: 8px 10px;\n"
  "              border-bottom: 1px solid #243040;\n"
  "              vertical-align: top; font-variant-numeric: tabular-nums; }\n"
  "    th { color: #8aa0b4; font-weight: 600; }\n"
  "    .note { background: #151c24; border-left: 3px solid #3b82f6;\n"
  "             padding: 12px 14px; margin: 16px 0; }\n"
  "    svg { margin: 8px 0 24px; }\n"
  "  </style>\n"
  "</head>\n"
  "<body>\n"
  "<main>\n"
  "  <h1>Pi MITM token report</h1>\n"
  "  <p class=\"muted\">Captured @CAPTURED@.\n"
  "  Model grok-4.6\n"
  "  via xai.\n"
  "  Run @RUN@.\n"
  "  Prices are list rates: input $@INPUT_RATE@/M,\n"
  "  cached $@CACHE_RATE@/M,\n"
  "  output $@OUTPUT_RATE@/M.</p>\n"
  "  <div class=\"cards\">\n"
  "    <div class=\"card\"><div class=\"muted\">LLM requests</div>\n"
  "      <div class=\"n\">@COUNT@</div></div>\n"
  "    <div class=\"card\"><div class=\"muted\">Input tokens sent</div>\n"
  "      <div class=\"n\">@INPUT@</div></div>\n"
  "    <div class=\"card\"><div class=\"muted\">Cached input</div>\n"
  "      <div class=\"n\">@CACHED@</div></div>\n"
  "    <div class=\"card\"><div class=\"muted\">Output tokens</div>\n"
  "      <div class=\"n\">@OUTPUT@</div></div>\n"
  "    <div class=\"card\"><div class=\"muted\">Estimated USD</div>\n"
  "      <div class=\"n\">$@COST@</div></div>\n"
  "  </div>\n"
  "  <div class=\"note\">\n"
  "    Bars are provider-reported tokens on each intercepted LLM HTTP request.\n"
  "    Summing input across turns counts every resend of growing context.\n"
  "    Tool and skill dollar figures are character-share estimates of input cost.\n"
  "    Prompt bodies are omitted from this file.\n"
  "  </div>\n"
  "  <h2>Tokens per request</h2>\n"
  "  @SVG@\n"
  "  <h2>User turns</h2>\n"
  "  <ol>@TURNS@</ol>\n"
  "  <p class=\"muted\">Task result:\n"
  "  @RESULT@.</p>\n"
  "  <h2>Request table</h2>\n"
  "  <table>\n"
  "    <thead><tr>\n"
  "      <th>#</th><th>Time</th><th>Input</th><th>Cached</th><th>Output</th>\n"
  "      <th>Reasoning</th><th>Request chars</th><th>Tools advertised</th>\n"
  "      <th>Messages</th><th>Est. USD</th><th>Invoked</th>\n"
  "    </tr></thead>\n"
  "    <tbody>\n"
  "      @ROWS@\n"
  "    </tbody>\n"
  "  </table>\n"
  "  <h2>Skills, MCP, and tools</h2>\n"
  "  <p class=\"muted\">Unique calls are distinct tool uses. Wire appearances count\n"
  "  every resend of that call in later requests. Tool schemas across requests:\n"
  "  @SCHEMA_CHARS@ characters,\n"
  "  about $@SCHEMA_COST@\n"
  "  of input cost.</p>\n"
  "  <table>\n"
  "    <thead><tr>\n"
  "      <th>Name</th><th>Kind</th><th>Unique calls</th><th>Wire appearances</th>\n"
  "      <th>Note</th><th>Est. USD</th>\n"
  "    </tr></thead>\n"
  "    <tbody>\n"
  "      @TOOLS@\n"
  "    </tbody>\n"
  "  </table>\n"
  "</main>\n"
  "</body>\n"
  "</html>\n";
