"""Walker CSS generated from the shared Base16 theme renderer."""

import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
HYPRLAND = ROOT / "home/user/themes/hyprland.nix"

# Non-empty rules in Walker 2.16.2 resources/themes/default/style.css.
# A custom style.css replaces that file, so the generated sheet must cover them.
REQUIRED_SELECTORS = [
    "popover",
    ".normal-icons",
    ".large-icons",
    "scrollbar",
    ".box-wrapper",
    ".preview-box",
    ".elephant-hint",
    ".placeholder",
    ".search-container",
    ".input placeholder",
    ".input selection",
    ".input",
    ".list",
    ".item-box",
    ".item-quick-activation",
    "child:selected .item-box",
    "row:selected .item-box",
    ".item-subtext",
    ".providerlist .item-subtext",
    ".item-image-text",
    ".preview",
    ".calc .item-text",
    ".symbols .item-image",
    ".todo.done .item-text-box",
    ".todo.urgent",
    ".todo.active",
    ".bluetooth.disconnected",
    ".preview .large-icons",
    ".keybinds",
    ".keybind-button",
    ".keybind-button:hover",
    ".keybind-bind",
    ".keybind-label",
    ".error",
    ":not(.calc).current",
    ".preview-content.archlinuxpkgs",
    ".preview-content.dnfpackages",
]

DARK = {
    f"base{index:02X}": f"{index:02x}{index:02x}{index:02x}"
    for index in range(16)
}
LIGHT = {
    f"base{index:02X}": f"{15 - index:02x}{15 - index:02x}{15 - index:02x}"
    for index in range(16)
}


def render(
    mode,
    palette,
    font="Liberation Sans",
    mono="JetBrainsMono Nerd Font",
    font_size=12,
):
    expression = f"""
      let
        hyprland = import {HYPRLAND} {{}};
        palette = builtins.fromJSON ''{json.dumps(palette)}'';
        appearance = {{
          font = {json.dumps(font)};
          monoFont = {json.dumps(mono)};
          fontSize = {font_size};
          rounding = 8;
          borderSize = 2;
          colors = {{}};
        }};
        rendered = hyprland.render {{
          mode = {json.dumps(mode)};
          inherit palette appearance;
        }};
      in {{
        assets = hyprland.assets;
        walker = hyprland.walker;
        names = builtins.attrNames rendered;
        css = rendered."walker.css";
      }}
    """
    raw = subprocess.check_output(
        ["nix", "eval", "--impure", "--json", "--expr", expression],
        text=True,
    )
    return json.loads(raw)


class LauncherThemeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.dark = render("dark", DARK)
        cls.light = render(
            "light",
            LIGHT,
            font='Quote "Face"',
            mono="Mono\\Face",
            font_size=14,
        )

    def test_theme_contract_and_seed_assets(self):
        for rendered in (self.dark, self.light):
            self.assertEqual(rendered["walker"]["theme"], "hyprland")
            self.assertEqual(rendered["walker"]["stylesheet"], "walker.css")
            self.assertEqual(
                rendered["walker"]["activePath"],
                ".local/state/theme-menu/active/walker.css",
            )
            self.assertIn("walker.css", rendered["assets"])
            self.assertIn("fuzzel.ini", rendered["assets"])
            missing = set(rendered["assets"]) - set(rendered["names"])
            self.assertEqual(missing, set())

    def test_css_uses_palette_fonts_and_walker_selectors(self):
        css = self.dark["css"]
        self.assertIn("Selected mode: dark. Generated by theme-menu.", css)
        self.assertIn("@define-color window_bg_color #000000;", css)
        self.assertIn("@define-color accent_bg_color #0d0d0d;", css)
        self.assertIn("@define-color selection #020202;", css)
        self.assertIn("@define-color muted #040404;", css)
        self.assertIn("@define-color error_bg_color #080808;", css)
        self.assertIn(
            'font-family: "Liberation Sans", "JetBrainsMono Nerd Font";',
            css,
        )
        self.assertIn("font-size: 12pt;", css)
        self.assertIn("font-size: 10pt;", css)
        self.assertIn("border-radius: 8px;", css)
        self.assertIn("border: 2px solid @accent_bg_color;", css)
        self.assertIn("background-color: transparent;", css)
        for selector in REQUIRED_SELECTORS:
            self.assertIn(selector, css)
        self.assertNotIn(
            "theme-menu", css.split("Generated by theme-menu.", 1)[1]
        )

    def test_light_mode_and_font_escaping_differ_from_dark(self):
        css = self.light["css"]
        self.assertIn("Selected mode: light. Generated by theme-menu.", css)
        self.assertIn("@define-color window_bg_color #0f0f0f;", css)
        self.assertNotIn("@define-color window_bg_color #000000;", css)
        self.assertIn('font-family: "Quote \\"Face\\"", "Mono\\\\Face";', css)
        self.assertIn("font-size: 14pt;", css)
        self.assertIn("font-size: 12pt;", css)


spec = importlib.util.spec_from_file_location(
    "launcher_theme_menu",
    ROOT / "home/config/appearance/theme_menu.py",
)
menu = importlib.util.module_from_spec(spec)
spec.loader.exec_module(menu)

WALKER_RESTART = ["systemctl", "--user", "try-restart", "walker.service"]


class WalkerPublishReloadTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        root = Path(self.tmp.name)
        catalogue = {
            "default": "tokyo-night",
            "palettes": {
                "tokyo-night": {"id": "tokyo-night", "label": "Tokyo Night"}
            },
        }
        self.controller = menu.Themes(
            catalogue,
            root / "state",
            root / "config",
            root / "greeter",
        )

    def publish(self, walker_installed, run_side_effect=None):
        def which(name):
            if name == "walker":
                return "/bin/walker" if walker_installed else None
            return f"/bin/{name}"

        with (
            patch.dict(menu.os.environ, {"THEME_MENU_PUBLISH": "1"}),
            patch.object(menu, "hyprland_session", return_value=True),
            patch.object(menu.shutil, "which", side_effect=which),
            patch.object(self.controller, "publish_greeter", return_value=[]),
            patch.object(self.controller, "_publish_gtk", return_value=[]),
            patch.object(self.controller, "_install_gtk_css", return_value=[]),
            patch.object(self.controller, "_reload_hyprland", return_value=[]),
            patch.object(self.controller, "_reload_waybar", return_value=[]),
            patch.object(menu.subprocess, "run") as run,
        ):
            if run_side_effect is None:
                run.return_value.returncode = 0
            else:
                run.side_effect = run_side_effect
            warnings = self.controller.publish_session()
        return warnings, run

    def test_hyprland_publish_restarts_walker_when_installed(self):
        warnings, run = self.publish(True)
        walker_calls = [
            call
            for call in run.call_args_list
            if call.args[0] == WALKER_RESTART
        ]
        self.assertEqual(len(walker_calls), 1)
        self.assertEqual(
            walker_calls[0].kwargs,
            {"capture_output": True, "timeout": 10, "check": True},
        )
        self.assertNotIn(
            "Launcher will use the theme on next startup.", warnings
        )

    def test_hyprland_publish_skips_walker_restart_when_absent(self):
        warnings, run = self.publish(False)
        for call in run.call_args_list:
            self.assertNotIn("walker.service", call.args[0])
        self.assertNotIn(
            "Launcher will use the theme on next startup.", warnings
        )

    def test_walker_restart_failure_warns_without_blocking_publish(self):
        def fail_walker(argv, **kwargs):
            if argv == WALKER_RESTART:
                raise subprocess.CalledProcessError(1, argv, stderr="failed")
            return subprocess.CompletedProcess(argv, 0)

        warnings, run = self.publish(True, fail_walker)
        self.assertIn("Launcher will use the theme on next startup.", warnings)
        self.assertEqual(run.call_args_list[0].args[0], WALKER_RESTART)
        self.assertIn(
            ["makoctl", "reload"],
            [call.args[0] for call in run.call_args_list],
        )

        def missing_systemctl(argv, **kwargs):
            if argv == WALKER_RESTART:
                raise OSError("systemctl missing")
            return subprocess.CompletedProcess(argv, 0)

        warnings, run = self.publish(True, missing_systemctl)
        self.assertIn("Launcher will use the theme on next startup.", warnings)
        self.assertTrue(run.called)


if __name__ == "__main__":
    unittest.main()
