[org/gnome/Weather]
locations=[<(uint32 2, <('London', 'EGWU', true, [(0.89971722940307675, -0.007272211034407213)], [(0.89884456477707964, -0.0020362232784242244)])>)>]
window-height=1376
window-maximized=false
window-width=840

[org/gnome/desktop/search-providers]
enabled=['org.gnome.Weather.desktop']
sort-order=['org.gnome.Settings.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Nautilus.desktop']

[org/gnome/shell/extensions/auto-move-windows]
application-list=['brave-browser.desktop:1', 'spotify.desktop:3', 'org.clementine_player.Clementine.desktop:3', 'slack.desktop:2', 'org.telegram.desktop.desktop:2', 'discord.desktop:2']

[org/gnome/shell/weather]
automatic-location=true
locations=[<(uint32 2, <('London', 'EGWU', true, [(0.89971722940307675, -0.007272211034407213)], [(0.89884456477707964, -0.0020362232784242244)])>)>]

[org/gnome/tweaks]
show-extensions-notice=false
