[org/gnome/Weather]
locations=[<(uint32 2, <('London', 'EGWU', true, [(0.89971722940307675, -0.007272211034407213)], [(0.89884456477707964, -0.0020362232784242244)])>)>]
window-height=1376
window-maximized=false
window-width=840

[org/gnome/calendar]
active-view='month'
window-maximized=false
window-size=(3432, 1400)

[org/gnome/desktop/notifications]
application-children=['org-gnome-settings', 'org-gnome-console', 'gnome-power-panel', 'zoom', 'slack', 'firefox', 'org-telegram-desktop', 'gnome-network-panel', 'org-gnome-epiphany', 'org-gnome-characters', 'gnome-printers-panel', 'org-gnome-evolution-alarm-notify', 'spotify']

[org/gnome/desktop/notifications/application/firefox]
application-id='firefox.desktop'

[org/gnome/desktop/notifications/application/gnome-network-panel]
application-id='gnome-network-panel.desktop'

[org/gnome/desktop/notifications/application/gnome-power-panel]
application-id='gnome-power-panel.desktop'

[org/gnome/desktop/notifications/application/gnome-printers-panel]
application-id='gnome-printers-panel.desktop'

[org/gnome/desktop/notifications/application/org-gnome-characters]
application-id='org.gnome.Characters.desktop'

[org/gnome/desktop/notifications/application/org-gnome-console]
application-id='org.gnome.Console.desktop'

[org/gnome/desktop/notifications/application/org-gnome-epiphany]
application-id='org.gnome.Epiphany.desktop'

[org/gnome/desktop/notifications/application/org-gnome-evolution-alarm-notify]
application-id='org.gnome.Evolution-alarm-notify.desktop'

[org/gnome/desktop/notifications/application/org-gnome-settings]
application-id='org.gnome.Settings.desktop'

[org/gnome/desktop/notifications/application/org-telegram-desktop]
application-id='org.telegram.desktop.desktop'

[org/gnome/desktop/notifications/application/slack]
application-id='slack.desktop'

[org/gnome/desktop/notifications/application/spotify]
application-id='spotify.desktop'

[org/gnome/desktop/notifications/application/zoom]
application-id='Zoom.desktop'

[org/gnome/desktop/peripherals/touchpad]
two-finger-scrolling-enabled=true

[org/gnome/desktop/search-providers]
enabled=['org.gnome.Weather.desktop']
sort-order=['org.gnome.Settings.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Nautilus.desktop']

[org/gnome/desktop/wm/keybindings]
close=['<Super>q']
minimize=@as []
move-to-workspace-1=['<Shift><Super>1']
move-to-workspace-2=['<Shift><Super>2']
move-to-workspace-3=['<Shift><Super>3']
move-to-workspace-4=['<Shift><Super>4']
move-to-workspace-5=['<Shift><Super>5']
move-to-workspace-6=['<Shift><Super>6']
move-to-workspace-7=['<Shift><Super>7']
move-to-workspace-8=['<Shift><Super>8']
move-to-workspace-9=['<Shift><Super>9']
switch-to-workspace-1=['<Super>1']
switch-to-workspace-2=['<Super>2']
switch-to-workspace-3=['<Super>3']
switch-to-workspace-4=['<Super>4']
switch-to-workspace-5=['<Super>5']
switch-to-workspace-6=['<Super>6']
switch-to-workspace-7=['<Super>7']
switch-to-workspace-8=['<Super>8']
switch-to-workspace-9=['<Super>9']
toggle-fullscreen=['<Super>f']

[org/gnome/desktop/wm/preferences]
auto-raise=false
button-layout='appmenu:close'
focus-mode='mouse'
num-workspaces=9
workspace-names=['web', 'chat', 'sound', 'video']

[org/gnome/mutter]
dynamic-workspaces=false
edge-tiling=false
overlay-key='Super_L'

[org/gnome/nautilus/preferences]
default-folder-viewer='icon-view'
migrated-gtk-settings=true
search-filter-time-type='last_modified'

[org/gnome/settings-daemon/plugins/color]
night-light-enabled=true
night-light-schedule-automatic=false
night-light-temperature=uint32 3482

[org/gnome/shell]
disabled-extensions=['windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'system-monitor@gnome-shell-extensions.gcampax.github.com', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'light-style@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com']
enabled-extensions=['pop-shell@system76.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'status-icons@gnome-shell-extensions.gcampax.github.com']
welcome-dialog-last-shown-version='45.5'

[org/gnome/shell/extensions/auto-move-windows]
application-list=['brave-browser.desktop:1', 'spotify.desktop:3', 'org.clementine_player.Clementine.desktop:3', 'slack.desktop:2', 'org.telegram.desktop.desktop:2', 'discord.desktop:2']

[org/gnome/shell/extensions/pop-shell]
active-hint = true
active-hint-border-radius = "uint32 1"
gap-inner = "uint32 1"
gap-outer = "uint32 1"
show-title = false
tile-by-default = true
focus-left = ["<Super>a"]
focus-down = ["<Super>s"]
focus-up = ["<Super>w"]
focus-right = ["<Super>d"]
activate-launcher = ["<Super>x"]
tile-move-left-global = ["<Shift><Super>a"]
tile-move-down-global = ["<Shift><Super>s"]
tile-move-up-global = ["<Shift><Super>w"]
tile-move-right-global = ["<Shift><Super>d"]
tile-resize-left = ["<Control><Shift>a", "<Shift>KP_Left", "<Shift>h"]
tile-resize-down = ["<Control><Shift>s", "<Shift>KP_Down", "<Shift>j"]
tile-resize-up = ["<Control><Shift>w", "<Shift>KP_Up", "<Shift>k"]
tile-resize-right = ["<Control><Shift>d", "<Shift>KP_Right", "<Shift>l"]

[org/gnome/shell/keybindings]
show-screenshot-ui=['<Control><Shift>s']
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []

[org/gnome/shell/weather]
automatic-location=true
locations=[<(uint32 2, <('London', 'EGWU', true, [(0.89971722940307675, -0.007272211034407213)], [(0.89884456477707964, -0.0020362232784242244)])>)>]

[org/gnome/tweaks]
show-extensions-notice=false
