return {
	'christoomey/vim-tmux-navigator',
	'nvim-lua/plenary.nvim', -- lua functions that many plugins use
	'christoomey/vim-tmux-navigator', -- tmux & split window navigation
	'inkarkat/vim-ReplaceWithRegister',
	'fedepujol/move.nvim',
  'xiyaowong/transparent.nvim',
  'tpope/vim-bundler',
  'sheerun/vim-polyglot',
  'junegunn/vim-easy-align',
  'RRethy/nvim-treesitter-textsubjects',
  'RRethy/nvim-treesitter-endwise',
  { 'whatyouhide/vim-textobj-erb',     dependencies = 'kana/vim-textobj-user' },
  { 'kana/vim-textobj-line',           dependencies = 'kana/vim-textobj-user' },
  { 'whatyouhide/vim-textobj-xmlattr', dependencies = 'kana/vim-textobj-user' },
  { 'b4winckler/vim-angry',            dependencies = 'kana/vim-textobj-user' },
  { 'michaeljsmith/vim-indent-object', dependencies = 'kana/vim-textobj-user' },
  { 'tek/vim-textobj-ruby',            dependencies = 'kana/vim-textobj-user' },
  { 'vimtaku/vim-textobj-keyvalue',    dependencies = 'kana/vim-textobj-user' },
  { 'bps/vim-textobj-python',          dependencies = 'kana/vim-textobj-user' },
  'christoomey/vim-sort-motion',
  'andymass/vim-matchup',
  'kylechui/nvim-surround',
  'tpope/vim-dispatch',
  'tpope/vim-rhubarb',
  'tpope/vim-unimpaired',
  'kevinhwang91/nvim-bqf',
  'vim-test/vim-test',
  'fatih/vim-go',
  'xiyaowong/nvim-cursorword',
  'fadein/vim-FIGlet',
  'sotte/presenting.vim',
  'xiyaowong/telescope-emoji.nvim',
  'stefandtw/quickfix-reflector.vim',
  'lepture/vim-jinja',
  'Glench/Vim-Jinja2-Syntax',
}
