# Immutable mode bundles copied to theme-menu/active at runtime. Keep the lock
# include variables-only: repeated Hyprlock blocks create additional widgets.
{ lib }:
let
  rgb = colour: "rgb(${colour})";
  hash = colour: "#${colour}";
  plain = colour: "${colour}ff";
  selection = (import ./render.nix { inherit lib; }).selectionPair;
in
{
  assets = [
    "hyprland.conf"
    "fuzzel.ini"
    "walker.css"
    "waybar.css"
    "hyprlock.conf"
    "gtk.css"
    "mako.conf"
    "colors.toml"
    "shell.toml"
  ];
  # Walker 2.16.2 loads themes/<name>/style.css and ignores themes/<name>.css.
  # That file must @import the published walker.css; a custom stylesheet
  # replaces the built-in default, so walker.css is the complete theme.
  walker = {
    theme = "hyprland";
    stylesheet = "walker.css";
    activePath = ".local/state/theme-menu/active/walker.css";
  };
  stateSubdir = "theme-menu";
  activeSubdir = "theme-menu/active";
  modeFile = "theme-menu/mode";

  render =
    {
      mode,
      palette,
      appearance,
    }:
    let
      inherit (appearance) font;
      mono = appearance.monoFont;
      fontSize = toString appearance.fontSize;
      rounding = toString appearance.rounding;
      borderSize = toString appearance.borderSize;
      activeBorder =
        if (appearance.colors.activeBorder or null) == null then
          rgb palette.base0D
        else
          appearance.colors.activeBorder;
      inactiveBorder =
        if (appearance.colors.inactiveBorder or null) == null then
          rgb palette.base03
        else
          appearance.colors.inactiveBorder;
      gtkTheme = if mode == "dark" then "adw-gtk3-dark" else "adw-gtk3";
      colorScheme = if mode == "dark" then "prefer-dark" else "prefer-light";
      cssString = value: builtins.replaceStrings [ "\\" "\"" "\n" ] [ "\\\\" "\\\"" " " ] value;
      subtextSize = toString (
        if appearance.fontSize > 2 then appearance.fontSize - 2 else appearance.fontSize
      );
      highlight = selection palette;
      variables = ''
        $theme_mode = ${mode}
        $theme_background = ${rgb palette.base00}
        $theme_surface = ${rgb palette.base01}
        $theme_selection = ${rgb highlight.bg}
        $theme_border = ${rgb palette.base03}
        $theme_muted = ${rgb palette.base04}
        $theme_text = ${rgb palette.base05}
        $theme_accent = ${rgb palette.base0D}
        $theme_active_border = ${activeBorder}
        $theme_inactive_border = ${inactiveBorder}
        $theme_fail = ${rgb palette.base08}
        $theme_check = ${rgb palette.base0B}
        $theme_font = ${font}
        $theme_mono_font = ${mono}
        $theme_font_size = ${fontSize}
        $theme_rounding = ${rounding}
        $theme_border_size = ${borderSize}
        $theme_gtk = ${gtkTheme}
        $theme_color_scheme = ${colorScheme}
      '';
    in
    {
      # Native Omarchy QML reads these role names through Commons/Color.qml.
      "colors.toml" = ''
        background = "${hash palette.base00}"
        foreground = "${hash palette.base05}"
        accent = "${hash palette.base0D}"
        red = "${hash palette.base08}"
        muted = "${hash palette.base04}"
      '';
      "shell.toml" = ''
        [font]
        base-size = ${toString (appearance.fontSize * 4 / 3)}
        [popups]
        background = "${hash palette.base00}"
        background-alpha = 0.94
        text = "${hash palette.base05}"
        border = "${hash palette.base0D}"
        accent = "${hash palette.base0D}"
        muted = "${hash palette.base04}"
        red = "${hash palette.base08}"
        orange = "${hash palette.base09}"
        yellow = "${hash palette.base0A}"
        green = "${hash palette.base0B}"
        teal = "${hash palette.base0C}"
      '';
      "hyprland.conf" = ''
        # Selected mode: ${mode}. Generated by theme-menu.
        ${variables}
        general {
            border_size = ${borderSize}
            col.active_border = ${activeBorder}
            col.inactive_border = ${inactiveBorder}
        }

        decoration {
            rounding = ${rounding}
        }

        misc {
            background_color = ${rgb palette.base00}
        }
      '';
      "fuzzel.ini" = ''
        # Selected mode: ${mode}. Generated by theme-menu.
        [main]
        font=${mono}:size=${fontSize}
        icons-enabled=no
        horizontal-pad=20
        vertical-pad=12
        inner-pad=8

        [colors]
        background=${plain palette.base00}
        text=${plain palette.base05}
        prompt=${plain palette.base0D}
        placeholder=${plain palette.base04}
        input=${plain palette.base05}
        match=${plain palette.base0D}
        selection=${plain highlight.bg}
        selection-text=${plain highlight.fg}
        selection-match=${plain palette.base0D}
        border=${plain palette.base0D}

        [border]
        width=${borderSize}
        radius=${rounding}
      '';
      # Complete Walker 2.16.2 stylesheet. Selectors follow
      # resources/themes/default/style.css; colours and type follow this palette.
      "walker.css" = ''
        /* Selected mode: ${mode}. Generated by theme-menu. */
        @define-color window_bg_color ${hash palette.base00};
        @define-color accent_bg_color ${hash palette.base0D};
        @define-color theme_fg_color ${hash palette.base05};
        @define-color error_bg_color ${hash palette.base08};
        @define-color error_fg_color ${hash palette.base00};
        @define-color surface ${hash palette.base01};
        @define-color selection ${hash highlight.bg};
        @define-color selection_text ${hash highlight.fg};
        @define-color border ${hash palette.base03};
        @define-color muted ${hash palette.base04};
        @define-color text ${hash palette.base05};

        * {
            all: unset;
        }

        * {
            font-family: "${cssString font}", "${cssString mono}";
            font-size: ${fontSize}pt;
        }

        window,
        .window {
            background-color: transparent;
        }

        popover {
            background: @surface;
            color: @text;
            border: ${borderSize}px solid @accent_bg_color;
            border-radius: ${rounding}px;
            padding: 10px;
        }

        .normal-icons {
            -gtk-icon-size: 16px;
        }

        .large-icons {
            -gtk-icon-size: 32px;
        }

        scrollbar {
            opacity: 0;
        }

        .box-wrapper {
            background: @window_bg_color;
            color: @text;
            padding: 20px;
            border-radius: ${rounding}px;
            border: ${borderSize}px solid @accent_bg_color;
        }

        .preview-box,
        .elephant-hint {
            color: @text;
        }

        .placeholder {
            color: @muted;
        }

        .search-container {
            border-radius: ${rounding}px;
        }

        .input placeholder {
            color: @muted;
            opacity: 1;
        }

        .input selection {
            background: @selection;
            color: @selection_text;
        }

        .input {
            caret-color: @accent_bg_color;
            background: @surface;
            color: @text;
            padding: 10px;
            border-radius: ${rounding}px;
        }

        .list {
            color: @text;
        }

        .item-box {
            border-radius: ${rounding}px;
            border: ${borderSize}px solid transparent;
            padding: 10px;
            color: @text;
        }

        .item-quick-activation {
            background: alpha(@accent_bg_color, 0.25);
            color: @text;
            border-radius: ${rounding}px;
            padding: 10px;
        }

        child:selected .item-box,
        row:selected .item-box {
            background: @selection;
            color: @selection_text;
            border-color: @accent_bg_color;
        }

        .item-subtext {
            font-size: ${subtextSize}pt;
            color: @muted;
        }

        .providerlist .item-subtext {
            font-size: unset;
            color: @text;
            opacity: 1;
        }

        .item-image-text {
            font-family: "${cssString mono}";
            font-size: 28px;
        }

        .preview {
            border: ${borderSize}px solid alpha(@accent_bg_color, 0.25);
            border-radius: ${rounding}px;
            color: @text;
        }

        .calc .item-text {
            font-family: "${cssString mono}";
            font-size: 24px;
        }

        .symbols .item-image {
            font-size: 24px;
        }

        .todo.done .item-text-box {
            opacity: 0.25;
        }

        .todo.urgent {
            font-size: 24px;
        }

        .todo.active {
            font-weight: bold;
        }

        .bluetooth.disconnected {
            opacity: 0.5;
        }

        .preview .large-icons {
            -gtk-icon-size: 64px;
        }

        .keybinds {
            padding-top: 10px;
            border-top: ${borderSize}px solid @border;
            font-size: ${subtextSize}pt;
            color: @muted;
        }

        .keybind-button {
            opacity: 0.5;
        }

        .keybind-button:hover {
            opacity: 0.75;
        }

        .keybind-bind {
            text-transform: lowercase;
            opacity: 0.35;
        }

        .keybind-label {
            padding: 2px 4px;
            border-radius: 4px;
            border: 1px solid @muted;
        }

        .error {
            padding: 10px;
            background: @error_bg_color;
            color: @error_fg_color;
            border-radius: ${rounding}px;
        }

        :not(.calc).current {
            font-style: italic;
        }

        .preview-content.archlinuxpkgs,
        .preview-content.dnfpackages {
            font-family: "${cssString mono}";
        }
      '';
      "waybar.css" = ''
        /* Selected mode: ${mode}. Generated by theme-menu. */
        @define-color background ${hash palette.base00};
        @define-color surface ${hash palette.base01};
        @define-color selection ${hash palette.base02};
        @define-color border ${hash palette.base03};
        @define-color muted ${hash palette.base04};
        @define-color text ${hash palette.base05};
        @define-color accent ${hash palette.base0D};
        @define-color red ${hash palette.base08};
        @define-color orange ${hash palette.base09};
        @define-color yellow ${hash palette.base0A};
        @define-color green ${hash palette.base0B};
        @define-color teal ${hash palette.base0C};
        @define-color purple ${hash palette.base0E};
        @define-color rose ${hash palette.base0F};

        * {
            font-family: "${font}", "${mono}";
            font-size: ${fontSize}pt;
            border-radius: ${rounding}px;
        }

        window#waybar {
            background: @background;
            color: @text;
            border: ${borderSize}px solid @border;
        }
      '';
      "hyprlock.conf" = ''
        # Selected mode: ${mode}. Variables only; do not add widgets here.
        ${variables}
      '';
      "mako.conf" = ''
        background-color=${hash palette.base00}
        text-color=${hash palette.base05}
        border-color=${hash palette.base0D}
        progress-color=over ${hash palette.base02}
        border-size=${borderSize}
        border-radius=${rounding}
        font=${mono} ${fontSize}
      '';
      "gtk.css" = ''
        /* Selected mode: ${mode}. Shared GTK and Brave colours and fonts. */
        @define-color theme_bg_color ${hash palette.base00};
        @define-color theme_fg_color ${hash palette.base05};
        @define-color theme_base_color ${hash palette.base01};
        @define-color theme_text_color ${hash palette.base05};
        @define-color theme_selected_bg_color ${hash highlight.bg};
        @define-color theme_selected_fg_color ${hash highlight.fg};
        @define-color accent_color ${hash palette.base0D};
        @define-color accent_bg_color ${hash palette.base0D};
        @define-color accent_fg_color ${hash palette.base00};
        @define-color window_bg_color ${hash palette.base00};
        @define-color window_fg_color ${hash palette.base05};
        @define-color view_bg_color ${hash palette.base01};
        @define-color view_fg_color ${hash palette.base05};
        @define-color headerbar_bg_color ${hash palette.base01};
        @define-color headerbar_fg_color ${hash palette.base05};
        @define-color sidebar_bg_color ${hash palette.base01};
        @define-color sidebar_fg_color ${hash palette.base05};
        @define-color card_bg_color ${hash palette.base01};
        @define-color card_fg_color ${hash palette.base05};
        @define-color popover_bg_color ${hash palette.base01};
        @define-color popover_fg_color ${hash palette.base05};
        @define-color dialog_bg_color ${hash palette.base00};
        @define-color dialog_fg_color ${hash palette.base05};
        @define-color destructive_bg_color ${hash palette.base08};
        @define-color destructive_fg_color ${hash palette.base00};
        @define-color success_color ${hash palette.base0B};
        @define-color warning_color ${hash palette.base0A};
        @define-color error_color ${hash palette.base08};

        window,
        dialog,
        .background {
            background-color: @theme_bg_color;
            color: @theme_fg_color;
        }

        * {
            font-family: "${font}", "${mono}";
        }
      '';
    };
}
