# Immutable mode bundles copied to theme-menu/active at runtime. Keep the lock
# include variables-only: repeated Hyprlock blocks create additional widgets.
_:
let
  rgb = colour: "rgb(${colour})";
  hash = colour: "#${colour}";
  plain = colour: "${colour}ff";
in
{
  assets = [
    "hyprland.conf"
    "fuzzel.ini"
    "waybar.css"
    "hyprlock.conf"
    "gtk.css"
    "mako.conf"
  ];
  stateSubdir = "theme-menu";
  activeSubdir = "theme-menu/active";
  modeFile = "theme-menu/mode";

  render =
    {
      mode,
      palette,
      appearance,
    }:
    let
      inherit (appearance) font;
      mono = appearance.monoFont;
      fontSize = toString appearance.fontSize;
      rounding = toString appearance.rounding;
      borderSize = toString appearance.borderSize;
      activeBorder =
        if (appearance.colors.activeBorder or null) == null then
          rgb palette.base0D
        else
          appearance.colors.activeBorder;
      inactiveBorder =
        if (appearance.colors.inactiveBorder or null) == null then
          rgb palette.base03
        else
          appearance.colors.inactiveBorder;
      gtkTheme = if mode == "dark" then "adw-gtk3-dark" else "adw-gtk3";
      colorScheme = if mode == "dark" then "prefer-dark" else "prefer-light";
      variables = ''
        $theme_mode = ${mode}
        $theme_background = ${rgb palette.base00}
        $theme_surface = ${rgb palette.base01}
        $theme_selection = ${rgb palette.base02}
        $theme_border = ${rgb palette.base03}
        $theme_muted = ${rgb palette.base04}
        $theme_text = ${rgb palette.base05}
        $theme_accent = ${rgb palette.base0D}
        $theme_active_border = ${activeBorder}
        $theme_inactive_border = ${inactiveBorder}
        $theme_fail = ${rgb palette.base08}
        $theme_check = ${rgb palette.base0B}
        $theme_font = ${font}
        $theme_mono_font = ${mono}
        $theme_font_size = ${fontSize}
        $theme_rounding = ${rounding}
        $theme_border_size = ${borderSize}
        $theme_gtk = ${gtkTheme}
        $theme_color_scheme = ${colorScheme}
      '';
    in
    {
      "hyprland.conf" = ''
        # Selected mode: ${mode}. Generated by theme-menu.
        ${variables}
        general {
            border_size = ${borderSize}
            col.active_border = ${activeBorder}
            col.inactive_border = ${inactiveBorder}
        }

        decoration {
            rounding = ${rounding}
        }

        misc {
            background_color = ${rgb palette.base00}
        }
      '';
      "fuzzel.ini" = ''
        # Selected mode: ${mode}. Generated by theme-menu.
        [main]
        font=${mono}:size=${fontSize}
        icons-enabled=no
        horizontal-pad=20
        vertical-pad=12
        inner-pad=8

        [colors]
        background=${plain palette.base00}
        text=${plain palette.base05}
        prompt=${plain palette.base0D}
        placeholder=${plain palette.base04}
        input=${plain palette.base05}
        match=${plain palette.base0D}
        selection=${plain palette.base02}
        selection-text=${plain palette.base05}
        selection-match=${plain palette.base0D}
        border=${plain palette.base0D}

        [border]
        width=${borderSize}
        radius=${rounding}
      '';
      "waybar.css" = ''
        /* Selected mode: ${mode}. Generated by theme-menu. */
        @define-color background ${hash palette.base00};
        @define-color surface ${hash palette.base01};
        @define-color selection ${hash palette.base02};
        @define-color border ${hash palette.base03};
        @define-color muted ${hash palette.base04};
        @define-color text ${hash palette.base05};
        @define-color accent ${hash palette.base0D};
        @define-color red ${hash palette.base08};
        @define-color orange ${hash palette.base09};
        @define-color yellow ${hash palette.base0A};
        @define-color green ${hash palette.base0B};
        @define-color teal ${hash palette.base0C};
        @define-color purple ${hash palette.base0E};
        @define-color rose ${hash palette.base0F};

        * {
            font-family: "${font}", "${mono}";
            font-size: ${fontSize}pt;
            border-radius: ${rounding}px;
        }

        window#waybar {
            background: @background;
            color: @text;
            border: ${borderSize}px solid @border;
        }
      '';
      "hyprlock.conf" = ''
        # Selected mode: ${mode}. Variables only; do not add widgets here.
        ${variables}
      '';
      "mako.conf" = ''
        background-color=${hash palette.base00}
        text-color=${hash palette.base05}
        border-color=${hash palette.base0D}
        progress-color=over ${hash palette.base02}
        border-size=${borderSize}
        border-radius=${rounding}
        font=${mono} ${fontSize}
      '';
      "gtk.css" = ''
        /* Selected mode: ${mode}. Shared GTK and Brave colours and fonts. */
        @define-color theme_bg_color ${hash palette.base00};
        @define-color theme_fg_color ${hash palette.base05};
        @define-color theme_base_color ${hash palette.base01};
        @define-color theme_text_color ${hash palette.base05};
        @define-color theme_selected_bg_color ${hash palette.base02};
        @define-color theme_selected_fg_color ${hash palette.base05};
        @define-color accent_color ${hash palette.base0D};
        @define-color accent_bg_color ${hash palette.base0D};
        @define-color accent_fg_color ${hash palette.base00};
        @define-color window_bg_color ${hash palette.base00};
        @define-color window_fg_color ${hash palette.base05};
        @define-color view_bg_color ${hash palette.base01};
        @define-color view_fg_color ${hash palette.base05};
        @define-color headerbar_bg_color ${hash palette.base01};
        @define-color headerbar_fg_color ${hash palette.base05};
        @define-color sidebar_bg_color ${hash palette.base01};
        @define-color sidebar_fg_color ${hash palette.base05};
        @define-color card_bg_color ${hash palette.base01};
        @define-color card_fg_color ${hash palette.base05};
        @define-color popover_bg_color ${hash palette.base01};
        @define-color popover_fg_color ${hash palette.base05};
        @define-color dialog_bg_color ${hash palette.base00};
        @define-color dialog_fg_color ${hash palette.base05};
        @define-color destructive_bg_color ${hash palette.base08};
        @define-color destructive_fg_color ${hash palette.base00};
        @define-color success_color ${hash palette.base0B};
        @define-color warning_color ${hash palette.base0A};
        @define-color error_color ${hash palette.base08};

        window,
        dialog,
        .background {
            background-color: @theme_bg_color;
            color: @theme_fg_color;
        }

        * {
            font-family: "${font}", "${mono}";
        }
      '';
    };
}
