import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:https';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,statSync,symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import test from 'node:test';
const bin=process.env.DAILY_AGENDA_BIN!,shim=process.env.DAILY_AGENDA_NETWORK!;
assert.ok(bin&&shim,'Set DAILY_AGENDA_BIN and DAILY_AGENDA_NETWORK');
const legacy=process.env.DAILY_AGENDA_LEGACY;
const token='fixture_token_0123456789';
const feed=`https://calendar.google.com/calendar/ical/user%40example.com/private-${token}/basic.ics`;
const day=new Date().toISOString().slice(0,10),stamp=day.replaceAll('-','');
const calendar=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:test\r\nDTSTART:${stamp}T090000Z\r\nDTEND:${stamp}T100000Z\r\nSUMMARY:Demo ${token} ${feed}\r\nLOCATION:Room ${token}\r\nDESCRIPTION:Join https://meet.google.com/abc-defg-hij\r\nURL:https://calendar.google.com/event?eid=test\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;
async function command(command:string,env:Record<string,string>){return await new Promise<{status:number|null;stdout:string;stderr:string}>((resolve,reject)=>{const parent=command===bin&&process.env.DAILY_AGENDA_PARENT_FIXTURE;const child=spawn(parent||command,parent?['cli','--refresh']:['--refresh'],{env:{...process.env,TZ:'UTC',...env},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';const timeout=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('Fixture process timed out'));},70_000);child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.on('error',reject);child.on('close',status=>{clearTimeout(timeout);resolve({status,stdout,stderr});});});}
async function scenario(mode:string,fn:(root:string,env:Record<string,string>,requests:any[])=>Promise<void>){const root=mkdtempSync(join(tmpdir(),'agenda-https-'));const key=join(root,'key.pem'),cert=join(root,'cert.pem');const ssl=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=calendar.google.com','-addext','subjectAltName=DNS:calendar.google.com','-addext','basicConstraints=critical,CA:TRUE'],{encoding:'utf8'});assert.equal(ssl.status,0,ssl.stderr);const requests:any[]=[];let calls=0;const server=createServer({key:readFileSync(key),cert:readFileSync(cert)},(req,res)=>{requests.push({method:req.method,url:req.url,headers:req.headers});calls++;if(mode==='redirect'){res.writeHead(302,{Location:'https://example.com/blocked'});res.end();}else if(mode==='status'){res.writeHead(403);res.end('No access '+token);}else if(mode==='size'){res.writeHead(200,{'Content-Length':2_000_001});res.end();}else if(mode==='type'){res.writeHead(200);res.end('not an iCalendar');}else if(mode==='overstate'){res.writeHead(200,{'Content-Length':Buffer.byteLength(calendar)+100});res.end(calendar);}else if(mode==='progress'){res.writeHead(200);let offset=0;const step=Math.ceil(calendar.length/5);res.write(calendar.slice(offset,offset+=step));const timer=setInterval(()=>{if(offset+step>=calendar.length){clearInterval(timer);res.end(calendar.slice(offset));}else res.write(calendar.slice(offset,offset+=step));},5100);}else if(mode==='bar-fail'&&calls%2===0){res.writeHead(500);res.end();}else if(mode==='slow'){res.writeHead(200);res.write(calendar.slice(0,50));setTimeout(()=>res.end(calendar.slice(50)),21_000);}else{res.writeHead(200,{'Content-Type':'text/calendar'});res.end(calendar);}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address==='object');const e={HOME:root,XDG_CACHE_HOME:join(root,'cache'),XDG_STATE_HOME:join(root,'state'),DAILY_CALENDAR_CREDENTIALS:join(root,'secret'),SSL_CERT_FILE:cert,NIX_SSL_CERT_FILE:cert,LD_PRELOAD:shim,AGENDA_FIXTURE_PORT:String(address.port),HTTPS_PROXY:'http://127.0.0.1:1',ALL_PROXY:'http://127.0.0.1:1'};writeFileSync(e.DAILY_CALENDAR_CREDENTIALS,JSON.stringify({Work:feed}),{mode:0o600});mkdirSync(join(root,'Notes',day),{recursive:true});writeFileSync(join(root,'Notes',day,'today.md'),'# Reminders\n- Fixture reminder\n');try{await fn(root,e,requests);}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));rmSync(root,{recursive:true,force:true});}}

test('private HTTPS refresh, request headers, proxy isolation and export parity',async()=>{await scenario('good',async(root,e,requests)=>{
 const native=await command(bin,e);assert.equal(native.status,0,native.stderr);assert.ok(!native.stdout.includes(token));assert.equal(requests.length,2);for(const request of requests){assert.equal(request.method,'GET');assert.equal(request.headers.host,'calendar.google.com');assert.equal(request.headers.accept,'text/calendar, text/plain');assert.equal(request.headers['accept-encoding'],'identity');assert.equal(request.headers.authorization,undefined);assert.equal(request.headers.cookie,undefined);}
 const path=join(root,'cache','daily-agenda','calendar.json'),bar=join(root,'state','omarchy','calendar-events.json');const saved=JSON.parse(readFileSync(path,'utf8')),rows=JSON.parse(readFileSync(bar,'utf8'));assert.equal(saved.events[0].summary,'Demo [redacted] [redacted]');assert.equal(rows.events[0].location,'Room [redacted]');assert.equal(rows.events[0].meetingUrl,'https://meet.google.com/abc-defg-hij');assert.equal(statSync(path).mode&0o777,0o600);assert.equal(statSync(bar).mode&0o777,0o600);assert.ok(!readFileSync(bar,'utf8').includes(token));if(legacy){const old=await command(legacy,e);assert.equal(old.status,0,old.stdout+old.stderr+' requests='+requests.length);const expected=JSON.parse(readFileSync(path,'utf8')),expectedBar=JSON.parse(readFileSync(bar,'utf8'));delete saved.fetched_at;delete expected.fetched_at;delete rows.syncedAt;delete expectedBar.syncedAt;assert.deepEqual(saved,expected);assert.deepEqual(rows,expectedBar);}
});});
test('redirects, HTTP errors, response bounds and invalid calendars retain cache',async()=>{for(const mode of ['redirect','status','size','type'])await scenario(mode,async(root,e,requests)=>{
 const path=join(root,'cache','daily-agenda','calendar.json');mkdirSync(join(root,'cache','daily-agenda'),{recursive:true});const saved=JSON.stringify({day,fetched_at:new Date().toISOString(),events:[]});writeFileSync(path,saved);const r=await command(bin,e);assert.equal(r.status,1,mode);assert.equal(requests.length,1,mode);assert.equal(readFileSync(path,'utf8'),saved);assert.ok(!r.stderr.includes(token));assert.ok(!r.stdout.includes(token));if(legacy){const old=await command(legacy,e);assert.equal(old.status,1);assert.equal(r.stdout,old.stdout);}
});});
test('declared certificate trust fails closed without credential diagnostics',async()=>{await scenario('good',async(root,e,requests)=>{const r=await command(bin,{...e,SSL_CERT_FILE:join(root,'missing.pem')});assert.equal(r.status,1);assert.equal(requests.length,0);assert.ok(!r.stderr.includes(token));assert.ok(!r.stdout.includes(token));});});
test('bar failure does not roll back the freshly written daily cache',async()=>{await scenario('bar-fail',async(root,e)=>{mkdirSync(join(root,'state','omarchy'),{recursive:true});const path=join(root,'state','omarchy','calendar-events.json');writeFileSync(path,'previous bar cache');const r=await command(bin,e);assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'Warning: Calendar bar export failed; the previous rail calendar was kept.\n');assert.equal(readFileSync(path,'utf8'),'previous bar cache');assert.equal(JSON.parse(readFileSync(join(root,'cache','daily-agenda','calendar.json'),'utf8')).events.length,1);});});
test('unsafe bar publication retains state and reports only the bounded warning',async()=>{await scenario('good',async(root,e)=>{mkdirSync(join(root,'state','omarchy'),{recursive:true});writeFileSync(join(root,'target'),'keep');symlinkSync(join(root,'target'),join(root,'state','omarchy','calendar-events.json'));const r=await command(bin,e);assert.equal(r.status,0);assert.equal(readFileSync(join(root,'target'),'utf8'),'keep');assert.equal(r.stderr,'Warning: Calendar bar export failed; the previous rail calendar was kept.\n');});});
test('complete calendars with overstated Content-Length retain legacy framing semantics',async()=>{await scenario('overstate',async(root,e)=>{const native=await command(bin,e);if(legacy){const old=await command(legacy,e);assert.equal(native.status,old.status,native.stderr+old.stderr);}assert.equal(native.status,0,native.stderr);});});
test('progressing transfers retain socket idle semantics beyond twenty seconds',async()=>{await scenario('progress',async(root,e)=>{const started=Date.now(),r=await command(bin,e);assert.equal(r.status,0,r.stderr);assert.ok(Date.now()-started>=40_000);});});
test('idle reads time out rather than accepting a stalled calendar',async()=>{await scenario('slow',async(root,e)=>{const started=Date.now(),r=await command(bin,e);assert.equal(r.status,1);assert.ok(Date.now()-started>=19_000);assert.ok(Date.now()-started<30_000);});});
