"""Encrypt a Hermes declaration directly to SOPS, never plaintext Git."""

import argparse
import base64
import json
from pathlib import Path
import subprocess

from hermes_declaration import RUNTIME

# These files are already generated by other Home Manager modules.
MANAGED_SCRIPTS = {
    "crunch-attention-check.sh",
    "hmrc-vat-messages-check.sh",
    "hmrc-vat-messages-telegram.sh",
    "weekly-hermes-update.sh",
    "apply-house-telegram.py",
}


def capture(home):
    home = Path(home)
    files = []

    def add(path, relative=None):
        if path.is_symlink() or not path.is_file():
            return  # Existing Home Manager links retain their original owner.
        data = path.read_bytes()
        if path.suffix != ".md" and b"/nix/store/" in data:
            raise ValueError(
                "An unmanaged file contains an ephemeral store reference; "
                "declare its source instead"
            )
        files.append(
            {
                "path": relative or str(path.relative_to(home)),
                "content": base64.b64encode(data).decode(),
                "executable": bool(path.stat().st_mode & 0o111),
            }
        )

    for name in [
        "config.yaml",
        "SOUL.md",
        "AGENTS.md",
        "profiles/qwen/config.yaml",
    ]:
        path = home / name
        if not path.is_file():
            raise ValueError("Required Hermes configuration is missing")
        add(path)
    for directory in ["skills", "scripts", "hooks", "plugins", "assets"]:
        for path in sorted((home / directory).rglob("*")):
            parts = path.relative_to(home / directory).parts
            if any(
                part.startswith(".") or part in {"__pycache__", "node_modules"}
                for part in parts
            ):
                continue
            if directory == "scripts" and path.name in MANAGED_SCRIPTS:
                continue
            add(path)
    plugin = home / "hermes-agent/plugins/memory/mem0-selfhosted"
    for path in sorted(plugin.rglob("*")):
        if "__pycache__" not in path.parts:
            add(
                path,
                str(
                    Path("plugins/mem0-selfhosted") / path.relative_to(plugin)
                ),
            )
    jobs = json.loads((home / "cron/jobs.json").read_text())["jobs"]
    declared_jobs = [
        {k: v for k, v in job.items() if k not in RUNTIME} for job in jobs
    ]
    for job in declared_jobs:
        if isinstance(job.get("repeat"), dict):
            job["repeat"] = {**job["repeat"], "completed": 0}
    seed_files = []
    # Preserve OAuth refresh changes; seed credentials on a clean rebuild.
    for name in ["auth.json", "profiles/qwen/auth.json"]:
        path = home / name
        if path.is_file() and not path.is_symlink():
            seed_files.append(
                {
                    "path": name,
                    "content": base64.b64encode(path.read_bytes()).decode(),
                }
            )
    return {
        "version": 1,
        "files": files,
        "seed_files": seed_files,
        "jobs": declared_jobs,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("home", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    declaration = capture(args.home)
    # The destination's repository supplies its recipient policy. Capture stdout
    # so failures cannot print plaintext or credentials.
    result = subprocess.run(
        [
            "sops",
            "--encrypt",
            "--input-type",
            "json",
            "--output-type",
            "json",
            "--filename-override",
            str(args.output),
            "/dev/stdin",
        ],
        input=json.dumps(declaration).encode(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        cwd=args.output.resolve().parent.parent,
    )
    if result.returncode:
        raise SystemExit("SOPS encryption failed; no declaration written")
    args.output.write_bytes(result.stdout)
    print(
        f"Encrypted {len(declaration['files'])} configuration files and "
        f"{len(declaration['jobs'])} job definitions"
    )
